### ISSUE TITLE
很棒，看你的日志，天天都在进步

### ISSUE THREAD

**Issue by luoliCHq** [fuweifu-vtoo/daily-work#1]
很棒，看你的日志，天天都在进步。
我也在看slam十四讲，我不搞这个方向，但偶然得到了一个turtlebot2，纯粹当兴趣搞搞玩了。

**Comment by fuweifu-vtoo** [comment]
哈哈哈我们一起加油，我也有在关注你的账号。
我也不是在做slam，因为一个项目涉及到一点，现在结束了，slam就先放一边了。
